<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="GetExcelData.aspx.cs" Inherits="Kampanjer.GetExcelData" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div>
        <asp:ValidationSummary ShowModelStateErrors="true" runat="server" />
        <asp:GridView ID="NokkelOrdGridview" ItemType="Kampanjer.Models.Keyword" runat="server"
            ShowFooter="True" GridLines="Vertical" CellPadding="4" CssClass="table table-striped table-bordered"
            SelectMethod="NokkelOrdGridview_GetData" UpdateMethod="NokkelOrdGridview_UpdateItem" DeleteMethod="NokkelOrdGridview_DeleteItem"
            AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">
        </asp:GridView>
    </div>



    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="false">
        <Columns>
            <asp:BoundField DataField="VendorItemNo" HeaderText="Varenummer" />
            <asp:BoundField DataField="ItemNo" HeaderText="Nr" />
        </Columns>
    </asp:GridView>
    <br />
    <asp:TextBox ID="txtCopied" runat="server" TextMode="MultiLine" AutoPostBack="true"
        OnTextChanged="PasteToGridView" Height="200" Width="400" />
    <script type="text/javascript">
        window.onload = function () {
            document.getElementById("<%=txtCopied.ClientID %>").onpaste = function () {
                var txt = this;
                setTimeout(function () {
                    __doPostBack(txt.name, '');
                }, 100);
            }
        };
    </script>


</asp:Content>
